import org.jetbrains.kotlin.gradle.plugin.KotlinPlatformJvmPlugin
import org.jetbrains.kotlin.gradle.targets.js.binaryen.BinaryenRootPlugin.Companion.kotlinBinaryenExtension

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library` apply true
    `maven-publish` apply true
    kotlin("jvm") version "2.1.10" apply true
    id("com.diffplug.spotless") version "6.19.0" apply true
}

allprojects {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}

allprojects {
    val javaVersion = 21
    group = "org.vicky.vicky_utils"
    version = "0.0.1-BETA"
    description = "VickyE's Utility Mod"

    apply(plugin = "java")
    apply(plugin = "kotlin")
    apply(plugin = "java-library")
    apply(plugin = "maven-publish")
    apply(plugin = "com.diffplug.spotless")

    configure<com.diffplug.gradle.spotless.SpotlessExtension> {
        ratchetFrom("origin/master")

        format("misc") {
            target(".gitignore")
            trimTrailingWhitespace()
            endWithNewline()
            indentWithTabs()
            indentWithSpaces(4)
        }

        kotlin {
            target("src/main/kotlin/**/*.kt")
            licenseHeader("/* Licensed under Apache-2.0 \$YEAR. */")
        }

        java {
            target("src/main/java/**/*.java")

            importOrder(
                "java", "javax", "org", "com", "com.diffplug", "", "#com.diffplug", "#"
            )
            removeUnusedImports()
            formatAnnotations()
            googleJavaFormat().apply {
                version = "1.23.0"
                style("GOOGLE")
                reflowLongStrings(true)
            }

            licenseHeader("/* Licensed under Apache-2.0 \$YEAR. */")
        }
    }

    publishing {
        publications.create<MavenPublication>("maven") {
            from(components["java"])
        }
    }

    dependencies {
        implementation(kotlin("stdlib-jdk8"))
        api("org.reflections:reflections:0.10.2")
    }

    tasks.withType<JavaCompile> {
        options.encoding = "UTF-8"
    }

    tasks.withType<Javadoc> {
        options.encoding = "UTF-8"
    }

    plugins.withType<KotlinPlatformJvmPlugin> {
        tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
            kotlinOptions {
                jvmTarget = "$javaVersion"
            }
        }
    }

    kotlin {
        jvmToolchain(javaVersion)
    }

    java {
        sourceCompatibility = JavaVersion.toVersion(javaVersion)
        targetCompatibility = JavaVersion.toVersion(javaVersion)
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(javaVersion))
        }
    }
}