/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "v-utls"

pluginManagement {
    repositories {
        maven {
            url = file("./blockbench-dissolver/build/local-repo").toURI()
        }
        mavenLocal()
        gradlePluginPortal()
    }
}
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}
include(":shared")
include(":blockbench-dissolver")
