info:
  namespace: vicky_utls
items:
  player_head_gui_size_1:
    enabled: true
    display_name: null_head
    resource:
      generate: false
      model_path: player_head_gui_size_1
      material: PLAYER_HEAD