/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */
version = "1.20.4-0.0.1-BETA"
repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }

    maven {
        url = uri("https://repo.extendedclip.com/content/repositories/placeholderapi/")
    }

    maven {
        url = uri("https://mvn.lumine.io/repository/maven-public/")
    }

    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://www.matteodev.it/spigot/public/maven/")
    }

    maven {
        url = uri("https://repo.codemc.io/repository/maven-snapshots/")
    }

    maven {
        url = uri("https://repo.dmulloy2.net/repository/public/")
    }

    maven {
        url = uri("https://maven.enginehub.org/repo/")
    }

    maven {
        url = uri("https://nexus.phoenixdevt.fr/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

tasks.shadowJar {
    // relocate("org.hibernate", "org.vicky.shadowed.hibernate")
    // relocate("org.jboss.logging", "org.vicky.shadowed.jboss.logging")
    relocate("net.wesjd", "org.vicky.shadowed.net.wesjd")
    exclude("org/hibernate/**")
    exclude("org/jboss/logging/**")
    exclude("jakarta/persistence/**")
    exclude("javax/**")
    exclude("org/antlr/**")
    exclude("org/glassfish/**")
    exclude("org/spongepowered/configurate/**")
    // include("org/vicky/utilities/**")
}

dependencies {
    implementation("io.github.vickye2:vicky-utils-core:all-0.0.1-BETA")
    implementation("org.reflections:reflections:0.10.2")
    implementation("jakarta.xml.bind:jakarta.xml.bind-api:4.0.2")
    implementation("jakarta.ws.rs:jakarta.ws.rs-api:4.0.0")
    implementation("org.jboss.logging:jboss-logging:3.5.3.Final")
    implementation("org.hibernate.orm:hibernate-core:6.4.1.Final")
    implementation("org.hibernate.orm:hibernate-community-dialects:6.3.1.Final")
    implementation("org.xerial:sqlite-jdbc:3.48.0.0")
    implementation("org.spongepowered:configurate-yaml:4.1.2")
    implementation("org.spongepowered:configurate-jackson:4.1.2")
    implementation("org.spongepowered:configurate-xml:4.1.2")
    implementation("net.wesjd:anvilgui:1.10.2-SNAPSHOT")
    implementation("io.github.toxicity188:BetterCommand:1.4.3")
    implementation("net.objecthunter:exp4j:0.4.8")
    runtimeOnly("org.glassfish.jaxb:jaxb-runtime:4.0.5")
    compileOnly("io.papermc.paper:paper-api:1.20.4-R0.1-SNAPSHOT")
    compileOnly("me.clip:placeholderapi:2.11.5")
    compileOnly("io.lumine:Mythic-Dist:5.6.1")
    compileOnly("com.comphenix.protocol:ProtocolLib:5.1.0")
    compileOnly("io.lumine:MythicLib-dist:1.6.2-SNAPSHOT")
    compileOnly("net.Indyuce:MMOCore-API:1.12.1-SNAPSHOT")
    compileOnly("dev.jorel:commandapi-bukkit-core:9.7.0")
    compileOnly("com.sk89q.worldguard:worldguard-bukkit:7.0.12")
    compileOnly("com.github.LoneDev6:api-itemsadder:3.6.1")
    compileOnly("dev.lone:LoneLibs:1.0.58")
    compileOnly("net.luckperms:api:5.4")
    compileOnly("io.github.toxicity188:BetterHud-standard-api:1.12")
    compileOnly("io.github.toxicity188:BetterHud-bukkit-api:1.12")
}